baseURL = 'https://4coresolutions.co'
languageCode = 'en-us'
title = '4CORE Solutions'
theme = 'hello-friend-ng'

PygmentsCodeFences = true
PygmentsStyle = "monokai"

paginate    = 10
rssLimit    = 10

archetypeDir    = "archetypes"
contentDir      = "content"
dataDir         = "data"
layoutDir       = "layouts"
publishDir      = "public"

buildDrafts     = false
buildFuture     = false
buildExpired    = false
canonifyURLs    = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders    = false
disableRSS      = false
disableSitemap  = false
disable404      = false
disableHugoGeneratorInject  =   false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "jc0re"

[blackfriday]
  hrefTargetBlank = true

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for index page
  homeSubtitle = "A Cybersecurity Services Company"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  #Enable theme toggle
  enableThemeToggle = true

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "4CORE Solutions"
  keywords = "4CORE, 4coresolutions, cybersecurity"
  images = [""]

  [params.footer]
    trademark = true
    rss = true
    copyright = true
    author = true

[taxonomies]
    category = "categories"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "4CORE Solutions"
    subtitle = "A Cybersecurity Informatics Company"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd /4coresolutions/dot/co"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "post"
    name       = "Posts"
    url        = "/posts"